name: Generate connector capabilities

on:
  push:
    branches:
      - main

jobs:
  calculate-capabilities:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELENG_GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -o connector ./cmd/baton-google-workspace

      - name: Run and save output
        env:
          BATON_ADMINISTRATOR_EMAIL: admin@example.com
          BATON_CUSTOMER_ID: 1234567890
        run: ./connector capabilities > baton_capabilities.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating baton capabilities.'
          add: 'baton_capabilities.json'